name: pozzo_predict
description: Pozzo Predict
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.7.0
  get_it: ^7.3.0
  stacked_services: ^1.0.2
  stacked: ^3.2.3
  flutter_svg: ^2.0.7
  email_validator: ^2.1.17
  google_fonts: ^6.1.0
  logger: ^2.0.1
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  dio: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/pngs/
    - assets/svgs/