// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMGJxdOEu6w3Yn4aHI3rb7yymkun_ssXc',
    appId: '1:500140532547:web:5f727e0cfd0be2465605f6',
    messagingSenderId: '500140532547',
    projectId: 'pozzo-predict',
    authDomain: 'pozzo-predict.firebaseapp.com',
    storageBucket: 'pozzo-predict.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg6gvujdqi87sEkF5Ewx4ugLYfePlwZ1k',
    appId: '1:500140532547:android:317154ad7a50bc6a5605f6',
    messagingSenderId: '500140532547',
    projectId: 'pozzo-predict',
    storageBucket: 'pozzo-predict.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJCYqt2tHaKXDKFdiF2YpzzbNbrtcMPlQ',
    appId: '1:500140532547:ios:485026804c6001875605f6',
    messagingSenderId: '500140532547',
    projectId: 'pozzo-predict',
    storageBucket: 'pozzo-predict.appspot.com',
    iosBundleId: 'com.adeola.pozzoPredict',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJCYqt2tHaKXDKFdiF2YpzzbNbrtcMPlQ',
    appId: '1:500140532547:ios:447a8cbdf0591b225605f6',
    messagingSenderId: '500140532547',
    projectId: 'pozzo-predict',
    storageBucket: 'pozzo-predict.appspot.com',
    iosBundleId: 'com.adeola.pozzoPredict.RunnerTests',
  );
}
